model = "gpt-5.2-codex"
model_reasoning_effort = "medium"
[features]
shell_snapshot = true
unified_exec = true
powershell_utf8 = true
collab = true

[notice.model_migrations]
"gpt-5.1-codex-mini" = "gpt-5.2-codex"

[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"
